version: "3.7"

services:
#
# MySQL database services
#  --skip-ssl options must remain
#  a custom root password for the root database user can be set in a .env file
#
    database:
        build:
            context: ./mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${LOCAL_MYSQL_ROOT_PASSWORD}
        command: --skip-ssl
        image: eyalabraham/sql_backend:${IMAGE_BUILD_TAG}
        container_name: ${DB_SERVICE_NAME}
        networks:
            - library-net
#        volumes:
#            - "./data:/var/lib/mysql"
#
# Catalog REST database interface service
#
    catalog:
        build:
            context: ./flask-services/src/catalogdbservice
        command: --host ${LOCAL_HOST} --db ${DB_SERVICE_NAME}
        depends_on:
            - database
        image: eyalabraham/catalog_db:${IMAGE_BUILD_TAG}
        container_name: ${CATALOG_DB_SERVICE_NAME}
        networks:
            - library-net
        ports:
            - "8001:5001"
#
# Borrowing REST database interface service
#
    borrow:
        build:
            context: ./flask-services/src/borrowingdbservice
        command: --host ${LOCAL_HOST} --db ${DB_SERVICE_NAME}
        depends_on:
            - database
        image: eyalabraham/borrowing_db:${IMAGE_BUILD_TAG}
        container_name: ${BORROW_DB_SERVICE_NAME}
        networks:
            - library-net
        ports:
            - "8002:5002"
#
# Patrons REST database interface service
#
    patron:
        build:
            context: ./flask-services/src/patronsdbservice
        command: --host ${LOCAL_HOST} --db ${DB_SERVICE_NAME}
        depends_on:
            - database
        image: eyalabraham/patrons_db:${IMAGE_BUILD_TAG}
        container_name: ${PATRON_DB_SERVICE_NAME}
        networks:
            - library-net
        ports:
            - "8003:5003"
#
# Library borrowing logic service REST interface
#
    liblogic:
        build:
            context: ./flask-services/src/borrowlogicservice
        command: --host ${LOCAL_HOST} --cat ${CATALOG_DB_SERVICE_NAME} --borrow ${BORROW_DB_SERVICE_NAME}
        depends_on:
            - catalog
            - borrow
            - patron
        image: eyalabraham/lib_logic:${IMAGE_BUILD_TAG}
        container_name: ${BORROW_LOGIC_SERVICE_NAME}
        networks:
            - library-net
        ports:
            - "8004:5004"
#
# Web front end
#  a custom local host IP address should be provided in the .env file
#  this is the web front end access address for your local browser.
#  service names are added via environment variables, a Django hack to use command line
#  variable is preferred but not implemented here.
#
    frontend:
        env_file:
            - ./sample.env
        build:
            context: ./django-frontend
        environment:
            - CATALOG_DB_SERVICE=${CATALOG_DB_SERVICE_NAME}
            - BORROW_DB_SERVICE=${BORROW_DB_SERVICE_NAME}
            - PATRON_DB_SERVICE=${PATRON_DB_SERVICE_NAME}
            - BORROW_LOGIC_SERVICE=${BORROW_LOGIC_SERVICE_NAME}
        command: ${LOCAL_HOST}:8000
        depends_on:
            - catalog
            - borrow
            - patron
            - liblogic
        image: eyalabraham/web_frontend:${IMAGE_BUILD_TAG}
        container_name: ${FRONTEND_SERVICE_NAME}
        networks:
            - library-net
        ports:
            - "8000:8000"

networks:
    library-net:
        driver: bridge
    