apiVersion: v1
kind: Service
metadata:
  name: borrowing-rest
  labels:
    app: docker-demo
    area: rest-service
    app.kubernetes.io/part-of: my-library-app
spec:
  type: ClusterIP
  selector:
    app: docker-demo
    tier: backend-borrowing-rest
  ports:
  - protocol: "TCP"
    port: 5002
    targetPort: 5002