#
# Note: before applying this PVC, make sure you have
#       1. Enabled iSCSI or FC access to storage
#       2. CSI driver installed 
#       3. Storage class named 'gold'
#       4. Array secret
#
# See here for details:
# https://www.ibm.com/support/knowledgecenter/SSRQ8T_1.0.0/csi_block_storage_kc_welcome.html
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-docker-demo
  labels:
    app: docker-demo
    area: backend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gold