apiVersion: v1
kind: Service
metadata:
  name: liblogic-rest
  labels:
    app: docker-demo
    area: rest-service
spec:
  type: ClusterIP
  selector:
    app: docker-demo
    tier: backend-liblogic-rest
  ports:
  - protocol: "TCP"
    port: 5004
    targetPort: 5004